# Optimality Gap and Computation Time

In [846]:
import pandas as pd
import json
import os
import matplotlib.image as mpimg
import matplotlib.pyplot as plt

In [847]:
naive_cols = ["naive_obj",  "naive_road_u", "naive_int_u", "naive_time", "naive_x1_count", "naive_x2_count", "naive_y_count", "naive_policy_sim"]
heu_cols = ["heu_obj",  "heu_road_u", "heu_int_u", "heu_time", "heu_x1_count", "heu_x2_count", "heu_y_count", "heu_policy_sim"]
solver_cols = ["solver_obj",  "solver_road_u", "solver_int_u", "solver_time", "solver_x1_count", "solver_x2_count", "solver_y_count", "solver_policy_sim"]
allRoadsDF = pd.DataFrame(columns = ["scenarioID"] + naive_cols + heu_cols + solver_cols)

for id in range(1, 8):
    with open(f"sol_heuristic/output_h1/scenario_{id}/meta_data.json", "r") as file:
        naive = json.load(file)
    with open(f"sol_heuristic/output_h2/scenario_{id}/meta_data.json", "r") as file:
        heuristic = json.load(file)
    with open(f"solver/output/scenario_{id}/meta_data.json", "r") as file:
        solver = json.load(file)

    allRoadsDF.loc[len(allRoadsDF), "scenarioID"] = id
    allRoadsDF.loc[allRoadsDF["scenarioID"] == id, naive_cols] = [
        naive["obj_val"]["total_utility"],
        naive["obj_val"]["road_utility"],
        naive["obj_val"]["int_utility"],
        naive["cal_time_sec"],
        naive["result_description"]["num_x1"],
        naive["result_description"]["num_x2"],
        naive["result_description"]["num_y"],
        naive["policy_similarity"]
    ]
    allRoadsDF.loc[allRoadsDF["scenarioID"] == id, heu_cols] = [
        heuristic["obj_val"]["total_utility"],
        heuristic["obj_val"]["road_utility"],
        heuristic["obj_val"]["int_utility"],
        heuristic["cal_time_sec"],
        heuristic["result_description"]["num_x1"],
        heuristic["result_description"]["num_x2"],
        heuristic["result_description"]["num_y"],
        heuristic["policy_similarity"]
    ]
    allRoadsDF.loc[allRoadsDF["scenarioID"] == id, solver_cols] = [
        solver["obj_val"]["total_utility"],
        solver["obj_val"]["road_utility"],
        solver["obj_val"]["int_utility"],
        solver["cal_time_sec"],
        solver["result_description"]["num_x1"],
        solver["result_description"]["num_x2"],
        solver["result_description"]["num_y"],
        solver["policy_similarity"]
    ]

In [848]:
naive_cols = ["naive_obj",  "naive_road_u", "naive_int_u", "naive_time", "naive_x1_count", "naive_x2_count", "naive_y_count", "naive_policy_sim"]
heu_cols = ["heu_obj",  "heu_road_u", "heu_int_u", "heu_time", "heu_x1_count", "heu_x2_count", "heu_y_count", "heu_policy_sim"]
solver_cols = ["solver_obj",  "solver_road_u", "solver_int_u", "solver_time", "solver_x1_count", "solver_x2_count", "solver_y_count", "solver_policy_sim"]
newLanesDF = pd.DataFrame(columns = ["scenarioID"] + naive_cols + heu_cols + solver_cols)

for id in range(1, 8):
    with open(f"sol_heuristic/output_h1/scenario_{id}_np/meta_data.json", "r") as file:
        naive = json.load(file)
    with open(f"sol_heuristic/output_h2/scenario_{id}_np/meta_data.json", "r") as file:
        heuristic = json.load(file)
    with open(f"solver/output/scenario_{id}_np/meta_data.json", "r") as file:
        solver = json.load(file)

    newLanesDF.loc[len(newLanesDF), "scenarioID"] = id
    newLanesDF.loc[newLanesDF["scenarioID"] == id, naive_cols] = [
        naive["obj_val"]["total_utility"],
        naive["obj_val"]["road_utility"],
        naive["obj_val"]["int_utility"],
        naive["cal_time_sec"],
        naive["result_description"]["num_x1"],
        naive["result_description"]["num_x2"],
        naive["result_description"]["num_y"],
        naive["policy_similarity"]
    ]
    newLanesDF.loc[newLanesDF["scenarioID"] == id, heu_cols] = [
        heuristic["obj_val"]["total_utility"],
        heuristic["obj_val"]["road_utility"],
        heuristic["obj_val"]["int_utility"],
        heuristic["cal_time_sec"],
        heuristic["result_description"]["num_x1"],
        heuristic["result_description"]["num_x2"],
        heuristic["result_description"]["num_y"],
        heuristic["policy_similarity"]
    ]
    newLanesDF.loc[newLanesDF["scenarioID"] == id, solver_cols] = [
        solver["obj_val"]["total_utility"],
        solver["obj_val"]["road_utility"],
        solver["obj_val"]["int_utility"],
        solver["cal_time_sec"],
        solver["result_description"]["num_x1"],
        solver["result_description"]["num_x2"],
        solver["result_description"]["num_y"],
        solver["policy_similarity"]
    ]

In [849]:
for col in allRoadsDF.columns:
    allRoadsDF[col] = allRoadsDF[col].astype(float)
allRoadsDF = allRoadsDF.round(3)
allRoadsDF["optgap_naive"] = (allRoadsDF["solver_obj"] - allRoadsDF["naive_obj"]) / allRoadsDF["solver_obj"]
allRoadsDF["optgap_heu"] = (allRoadsDF["solver_obj"] - allRoadsDF["heu_obj"]) / allRoadsDF["solver_obj"]
allRoadsDF["scenarioID"] = allRoadsDF["scenarioID"].astype(int).astype(str)
allRoadsDF.set_index("scenarioID", inplace = True)

### All Roads

In [850]:
allRoadsDF[['naive_obj', "heu_obj", "solver_obj", "optgap_naive", "optgap_heu", "naive_time", "heu_time", "solver_time", "naive_policy_sim", "heu_policy_sim","solver_policy_sim"]]

,naive_obj,heu_obj,solver_obj,optgap_naive,optgap_heu,naive_time,heu_time,solver_time,naive_policy_sim,heu_policy_sim,solver_policy_sim
scenarioID,,,,,,,,,,,
1,875.656,1611.444,3227.616,0.728699,0.500732,0.679,4.817,115.417,0.675,0.646,0.459
2,2156.358,3163.345,5582.360,0.613719,0.433332,5.291,18.749,227.437,0.589,0.607,0.471
3,4352.918,5563.416,9291.719,0.531527,0.401250,27.761,59.472,151.460,0.531,0.486,0.491
4,2133.696,3070.193,4883.118,0.563046,0.371264,6.994,20.782,190.579,0.589,0.607,0.463
5,2111.033,2977.040,4682.408,0.549157,0.364207,6.627,21.809,46.559,0.589,0.607,0.455
6,1413.088,1954.572,4134.308,0.658204,0.527231,8.112,21.307,298.679,0.562,0.501,0.464
7,2687.503,3909.579,6850.217,0.607676,0.429277,3.566,14.837,480.525,0.625,0.638,0.471

In [851]:
allRoadsDF[['naive_x1_count', 'naive_y_count', 'heu_x1_count', "heu_y_count"]]

            naive_x1_count  naive_y_count  heu_x1_count  heu_y_count
scenarioID
1                    166.0          164.0         264.0        324.0
2                    399.0          443.0         551.0        679.0
3                    893.0         1017.0        1154.0       1418.0
4                    399.0          443.0         551.0        679.0
5                    399.0          443.0         551.0        679.0
6                    405.0          260.0         453.0        412.0
7                    400.0          570.0         539.0        842.0

In [852]:
for col in newLanesDF.columns:
    newLanesDF[col] = newLanesDF[col].astype(float)
newLanesDF = newLanesDF.round(3)
newLanesDF["optgap_naive"] = (newLanesDF["solver_obj"] - newLanesDF["naive_obj"]) / newLanesDF["solver_obj"]
newLanesDF["optgap_heu"] = (newLanesDF["solver_obj"] - newLanesDF["heu_obj"]) / newLanesDF["solver_obj"]
newLanesDF["scenarioID"] = newLanesDF["scenarioID"].astype(int).astype(str) + "_np"
newLanesDF.set_index("scenarioID", inplace = True)

### Only Consider Roads without Bike Lanes

np refers to new policy

In [853]:
newLanesDF[['naive_obj', "heu_obj", "solver_obj", "optgap_naive", "optgap_heu", "naive_time", "heu_time", "solver_time"]]

,naive_obj,heu_obj,solver_obj,optgap_naive,optgap_heu,naive_time,heu_time,solver_time
scenarioID,,,,,,,,
1_np,72.849,65.964,723.549,0.899317,0.908833,0.046,0.056,13.891
2_np,287.001,205.195,1314.097,0.781598,0.843851,0.120,0.217,12.771
3_np,486.983,528.061,1815.270,0.731730,0.709101,0.287,0.725,22.083
4_np,318.507,206.990,1150.172,0.723079,0.820036,0.120,0.205,9.634
5_np,350.014,208.786,1109.711,0.684590,0.811856,0.167,0.202,3.423
6_np,195.632,254.543,1026.584,0.809434,0.752049,0.148,0.457,16.588
7_np,313.019,635.505,1542.348,0.797050,0.587963,0.113,0.489,24.366

In [854]:
newLanesDF[['naive_obj', "heu_obj", "solver_obj", "optgap_naive", "optgap_heu", "naive_time", "heu_time", "solver_time"]].to_excel("analysis_results/newPolicy.xlsx")

In [855]:
cols = ['naive_obj', "heu_obj", "solver_obj", "optgap_naive", "optgap_heu", "naive_time", "heu_time", "solver_time", "naive_policy_sim", "heu_policy_sim","solver_policy_sim"]
pd.concat([allRoadsDF[cols], newLanesDF[cols]]).to_excel("analysis_results/result_table.xlsx")

# Fake Data

In [856]:
full = pd.DataFrame()
for file in os.listdir("./Experiments/outputs"):
    data = pd.read_excel(f"./Experiments/outputs/{file}", index_col=0)
    full = pd.concat([full, data])

In [857]:
full.columns

Index(['scenarioID', 'naiveObjVal', 'naiveTime', 'naiveX1num', 'naiveX2num',
       'naiveYnum', 'heuObjVal', 'heuTime', 'heuX1num', 'heuX2num', 'heuYnum',
       'solverObjVal', 'solverTime', 'solverX1num', 'solverX2num',
       'solverYnum', 'optGapNaive', 'optGapHeu'],
      dtype='object')

In [858]:
result = full.groupby("scenarioID").agg({
    "naiveObjVal": ["mean", "std"],
    "naiveTime": ["mean", "std"],
    "heuObjVal": ["mean", "std"],
    "heuTime": ["mean", "std"],
    "solverObjVal": ["mean", "std"],
    "solverTime": ["mean", "std"],
    "optGapNaive": ["mean", "std"],
    "optGapHeu": ["mean", "std"]
})
result

            naiveObjVal             naiveTime              heuObjVal  \
                   mean         std      mean       std         mean
scenarioID
1            580.590295   36.563111  0.473556  0.144205  1246.896266
2           1240.844591   58.864454  1.205284  0.244777  2428.028526
3           2854.852644  106.476422  5.396253  0.576939  4817.361892
4           2565.400391   96.788272  1.113493  0.170383  2823.524275
5           3879.851290  221.251492  1.116027  0.166826  3293.483044
6           1177.814204   43.046902  3.917045  0.922279  2022.896389
7           1265.983321   65.111629  0.985292  0.310865  2819.601361
1_np         112.115069   17.930086  0.055274  0.012307   231.155030
2_np         218.114112   20.594486  0.107105  0.017820   435.472332
3_np         345.243830   25.516460  0.229263  0.242407   666.503944
4_np         514.755834   68.757779  0.111185  0.026796   535.194932
5_np         834.356184  113.061301  0.109896  0.024439   657.876731
6_np         231.946050   29.339621  0.121069  0.031148   382.558379
7_np         226.360619   27.878421  0.158917  0.139286   509.642390

                          heuTime            solverObjVal             \
                   std       mean       std          mean        std
scenarioID
1            55.914030   4.939990  0.848091   3724.107634  52.570543
2            83.551830  13.944222  1.836784   6545.575854  77.296600
3           120.186102  42.902145  3.827065  10790.322051  82.995317
4            98.566675  12.837924  1.376391   5161.375230  60.849031
5           142.509834  13.167693  1.359588   4835.993458  80.179019
6            70.661992  22.456104  2.963813   5921.878462  49.300767
7           130.176288  12.617377  2.711866   6934.876257  77.810521
1_np         32.192754   0.193231  0.057503    733.025600  19.273670
2_np         37.370512   0.441498  0.101570   1305.213747  33.337949
3_np         47.604950   0.990777  0.369345   1822.616551  28.185284
4_np         43.385612   0.480867  0.127822   1091.276744  25.864451
5_np         47.464982   0.497919  0.134390   1219.827479  38.011373
6_np         24.963873   0.612344  0.136511   1210.501337  19.736838
7_np         38.201019   0.467451  0.152017   1367.833586  42.468240

           solverTime            optGapNaive           optGapHeu
                 mean        std        mean       std      mean       std
scenarioID
1            5.912671   0.926632    0.844057  0.010300  0.665157  0.014853
2            4.994480   0.455390    0.810431  0.008657  0.628994  0.013903
3            4.696483   0.380354    0.735445  0.009075  0.553552  0.010442
4            5.096794   0.295096    0.502871  0.020293  0.452956  0.017977
5            4.638644   0.274550    0.197904  0.039991  0.318847  0.030134
6           11.232089  29.616319    0.801088  0.007619  0.658407  0.011478
7            6.044125   1.268884    0.817458  0.008936  0.593386  0.018929
1_np         1.513570   0.278452    0.847035  0.024248  0.684592  0.043805
2_np         1.520194   0.228629    0.832900  0.015084  0.666265  0.028383
3_np         1.885786   0.552897    0.810534  0.014383  0.634314  0.025636
4_np         1.517011   0.298707    0.528286  0.062713  0.509387  0.040379
5_np         1.325415   0.173330    0.316109  0.089298  0.460423  0.039175
6_np         1.578487   0.251748    0.808260  0.025108  0.683877  0.021463
7_np         1.783128   0.411415    0.834493  0.020013  0.627070  0.030027

In [859]:
result.to_excel("Experiments/result_table.xlsx")