# Optimality Gap and Computation Time

In [243]:
import pandas as pd
import json
import os
import matplotlib.image as mpimg
import matplotlib.pyplot as plt

In [244]:
naive_cols = ["naive_obj",  "naive_road_u", "naive_int_u", "naive_time", "naive_x1_count", "naive_x2_count", "naive_y_count", "naive_policy_sim"]
heu_cols = ["heu_obj",  "heu_road_u", "heu_int_u", "heu_time", "heu_x1_count", "heu_x2_count", "heu_y_count", "heu_policy_sim"]
solver_cols = ["solver_obj",  "solver_road_u", "solver_int_u", "solver_time", "solver_x1_count", "solver_x2_count", "solver_y_count", "solver_policy_sim"]
allRoadsDF = pd.DataFrame(columns = ["scenarioID"] + naive_cols + heu_cols + solver_cols)

for id in range(1, 8):
    with open(f"sol_heuristic/output_h1/scenario_{id}/meta_data.json", "r") as file:
        naive = json.load(file)
    with open(f"sol_heuristic/output_h2/scenario_{id}/meta_data.json", "r") as file:
        heuristic = json.load(file)
    with open(f"solver/output/scenario_{id}/meta_data.json", "r") as file:
        solver = json.load(file)

    allRoadsDF.loc[len(allRoadsDF), "scenarioID"] = id
    allRoadsDF.loc[allRoadsDF["scenarioID"] == id, naive_cols] = [
        naive["obj_val"]["total_utility"],
        naive["obj_val"]["road_utility"],
        naive["obj_val"]["int_utility"],
        naive["cal_time_sec"],
        naive["result_description"]["num_x1"],
        naive["result_description"]["num_x2"],
        naive["result_description"]["num_y"],
        naive["policy_similarity"]
    ]
    allRoadsDF.loc[allRoadsDF["scenarioID"] == id, heu_cols] = [
        heuristic["obj_val"]["total_utility"],
        heuristic["obj_val"]["road_utility"],
        heuristic["obj_val"]["int_utility"],
        heuristic["cal_time_sec"],
        heuristic["result_description"]["num_x1"],
        heuristic["result_description"]["num_x2"],
        heuristic["result_description"]["num_y"],
        heuristic["policy_similarity"]
    ]
    allRoadsDF.loc[allRoadsDF["scenarioID"] == id, solver_cols] = [
        solver["obj_val"]["total_utility"],
        solver["obj_val"]["road_utility"],
        solver["obj_val"]["int_utility"],
        solver["cal_time_sec"],
        solver["result_description"]["num_x1"],
        solver["result_description"]["num_x2"],
        solver["result_description"]["num_y"],
        solver["policy_similarity"]
    ]

In [245]:
naive_cols = ["naive_obj",  "naive_road_u", "naive_int_u", "naive_time", "naive_x1_count", "naive_x2_count", "naive_y_count", "naive_policy_sim"]
heu_cols = ["heu_obj",  "heu_road_u", "heu_int_u", "heu_time", "heu_x1_count", "heu_x2_count", "heu_y_count", "heu_policy_sim"]
solver_cols = ["solver_obj",  "solver_road_u", "solver_int_u", "solver_time", "solver_x1_count", "solver_x2_count", "solver_y_count", "solver_policy_sim"]
newLanesDF = pd.DataFrame(columns = ["scenarioID"] + naive_cols + heu_cols + solver_cols)

for id in range(1, 8):
    with open(f"sol_heuristic/output_h1/scenario_{id}_np/meta_data.json", "r") as file:
        naive = json.load(file)
    with open(f"sol_heuristic/output_h2/scenario_{id}_np/meta_data.json", "r") as file:
        heuristic = json.load(file)
    with open(f"solver/output/scenario_{id}_np/meta_data.json", "r") as file:
        solver = json.load(file)

    newLanesDF.loc[len(newLanesDF), "scenarioID"] = id
    newLanesDF.loc[newLanesDF["scenarioID"] == id, naive_cols] = [
        naive["obj_val"]["total_utility"],
        naive["obj_val"]["road_utility"],
        naive["obj_val"]["int_utility"],
        naive["cal_time_sec"],
        naive["result_description"]["num_x1"],
        naive["result_description"]["num_x2"],
        naive["result_description"]["num_y"],
        naive["policy_similarity"]
    ]
    newLanesDF.loc[newLanesDF["scenarioID"] == id, heu_cols] = [
        heuristic["obj_val"]["total_utility"],
        heuristic["obj_val"]["road_utility"],
        heuristic["obj_val"]["int_utility"],
        heuristic["cal_time_sec"],
        heuristic["result_description"]["num_x1"],
        heuristic["result_description"]["num_x2"],
        heuristic["result_description"]["num_y"],
        heuristic["policy_similarity"]
    ]
    newLanesDF.loc[newLanesDF["scenarioID"] == id, solver_cols] = [
        solver["obj_val"]["total_utility"],
        solver["obj_val"]["road_utility"],
        solver["obj_val"]["int_utility"],
        solver["cal_time_sec"],
        solver["result_description"]["num_x1"],
        solver["result_description"]["num_x2"],
        solver["result_description"]["num_y"],
        solver["policy_similarity"]
    ]

In [246]:
for col in allRoadsDF.columns:
    allRoadsDF[col] = allRoadsDF[col].astype(float)
allRoadsDF = allRoadsDF.round(3)
allRoadsDF["optgap_naive"] = (allRoadsDF["solver_obj"] - allRoadsDF["naive_obj"]) / allRoadsDF["solver_obj"]
allRoadsDF["optgap_heu"] = (allRoadsDF["solver_obj"] - allRoadsDF["heu_obj"]) / allRoadsDF["solver_obj"]
allRoadsDF["scenarioID"] = allRoadsDF["scenarioID"].astype(int).astype(str)
allRoadsDF.set_index("scenarioID", inplace = True)

### All Roads

In [247]:
allRoadsDF[['naive_obj', "heu_obj", "solver_obj", "optgap_naive", "optgap_heu", "naive_time", "heu_time", "solver_time"]]

,naive_obj,heu_obj,solver_obj,optgap_naive,optgap_heu,naive_time,heu_time,solver_time
scenarioID,,,,,,,,
1,609.525,1370.504,2216.439,0.724998,0.381664,0.618,0.735,203.859
2,1410.453,2860.414,3873.162,0.635839,0.261478,2.472,2.596,121.322
3,2640.482,5499.717,6533.486,0.595854,0.158226,5.045,4.794,140.228
4,1668.082,2872.325,3877.472,0.569802,0.259227,2.320,1.948,74.996
5,1925.710,2884.236,4443.651,0.566638,0.350931,3.843,2.472,13.888
6,1419.619,2877.097,3874.942,0.633641,0.257512,1.746,2.617,113.691
7,1434.024,2862.465,3872.869,0.629726,0.260893,1.473,2.075,87.234

In [248]:
for col in newLanesDF.columns:
    newLanesDF[col] = newLanesDF[col].astype(float)
newLanesDF = newLanesDF.round(3)
newLanesDF["optgap_naive"] = (newLanesDF["solver_obj"] - newLanesDF["naive_obj"]) / newLanesDF["solver_obj"]
newLanesDF["optgap_heu"] = (newLanesDF["solver_obj"] - newLanesDF["heu_obj"]) / newLanesDF["solver_obj"]
newLanesDF["scenarioID"] = newLanesDF["scenarioID"].astype(int).astype(str) + "_np"
newLanesDF.set_index("scenarioID", inplace = True)

,naive_obj,naive_road_u,naive_int_u,naive_time,naive_x1_count,naive_x2_count,naive_y_count,naive_policy_sim,heu_obj,heu_road_u,...,solver_obj,solver_road_u,solver_int_u,solver_time,solver_x1_count,solver_x2_count,solver_y_count,solver_policy_sim,optgap_naive,optgap_heu
scenarioID,,,,,,,,,,,,,,,,,,,,,
1_np,41.891,146.930,15.631,0.079,30.0,0.0,3.0,NaN,212.338,278.760,...,487.957,97.173,390.784,27.664,136.0,0.0,116.0,NaN,0.914150,0.564843
2_np,195.632,363.853,153.577,0.247,77.0,0.0,30.0,NaN,521.656,586.584,...,877.482,177.542,699.940,21.797,248.0,0.0,212.0,NaN,0.777053,0.405508
3_np,330.547,594.951,264.446,0.314,122.0,1.0,53.0,NaN,734.942,796.975,...,1220.897,247.044,973.854,22.365,337.0,1.0,292.0,NaN,0.729259,0.398031
4_np,258.715,363.853,153.577,0.173,77.0,0.0,30.0,NaN,546.004,586.584,...,902.674,506.084,396.590,7.506,219.0,23.0,192.0,NaN,0.713390,0.395126
5_np,321.798,363.853,153.577,0.169,77.0,0.0,30.0,NaN,570.352,586.584,...,1068.208,998.819,69.389,2.028,63.0,101.0,85.0,NaN,0.698750,0.466067
6_np,194.939,381.120,148.394,0.205,74.0,1.0,29.0,NaN,532.686,689.391,...,877.943,179.760,698.183,27.022,245.0,2.0,211.0,NaN,0.777959,0.393257
7_np,195.632,363.853,153.577,0.156,77.0,0.0,30.0,NaN,529.071,545.272,...,877.460,177.560,699.900,21.436,248.0,0.0,212.0,NaN,0.777047,0.397043

### Only Consider Roads without Bike Lanes

np refers to new policy

In [249]:
newLanesDF[['naive_obj', "heu_obj", "solver_obj", "optgap_naive", "optgap_heu", "naive_time", "heu_time", "solver_time"]]

,naive_obj,heu_obj,solver_obj,optgap_naive,optgap_heu,naive_time,heu_time,solver_time
0,41.891,212.338,487.957,0.914150,0.564843,0.079,0.159,27.664
1,195.632,521.656,877.482,0.777053,0.405508,0.247,0.262,21.797
2,330.547,734.942,1220.897,0.729259,0.398031,0.314,0.503,22.365
3,258.715,546.004,902.674,0.713390,0.395126,0.173,0.540,7.506
4,321.798,570.352,1068.208,0.698750,0.466067,0.169,0.253,2.028
5,194.939,532.686,877.943,0.777959,0.393257,0.205,0.214,27.022
6,195.632,529.071,877.460,0.777047,0.397043,0.156,0.236,21.436