# Optimality Gap and Computation Time

In [361]:
import pandas as pd
import json
import os
import matplotlib.image as mpimg
import matplotlib.pyplot as plt

In [362]:
naive_cols = ["naive_obj",  "naive_road_u", "naive_int_u", "naive_time", "naive_x1_count", "naive_x2_count", "naive_y_count", "naive_policy_sim"]
heu_cols = ["heu_obj",  "heu_road_u", "heu_int_u", "heu_time", "heu_x1_count", "heu_x2_count", "heu_y_count", "heu_policy_sim"]
solver_cols = ["solver_obj",  "solver_road_u", "solver_int_u", "solver_time", "solver_x1_count", "solver_x2_count", "solver_y_count", "solver_policy_sim"]
allRoadsDF = pd.DataFrame(columns = ["scenarioID"] + naive_cols + heu_cols + solver_cols)

for id in range(1, 8):
    with open(f"sol_heuristic/output_h1/scenario_{id}/meta_data.json", "r") as file:
        naive = json.load(file)
    with open(f"sol_heuristic/output_h2/scenario_{id}/meta_data.json", "r") as file:
        heuristic = json.load(file)
    with open(f"solver/output/scenario_{id}/meta_data.json", "r") as file:
        solver = json.load(file)

    allRoadsDF.loc[len(allRoadsDF), "scenarioID"] = id
    allRoadsDF.loc[allRoadsDF["scenarioID"] == id, naive_cols] = [
        naive["obj_val"]["total_utility"],
        naive["obj_val"]["road_utility"],
        naive["obj_val"]["int_utility"],
        naive["cal_time_sec"],
        naive["result_description"]["num_x1"],
        naive["result_description"]["num_x2"],
        naive["result_description"]["num_y"],
        naive["policy_similarity"]
    ]
    allRoadsDF.loc[allRoadsDF["scenarioID"] == id, heu_cols] = [
        heuristic["obj_val"]["total_utility"],
        heuristic["obj_val"]["road_utility"],
        heuristic["obj_val"]["int_utility"],
        heuristic["cal_time_sec"],
        heuristic["result_description"]["num_x1"],
        heuristic["result_description"]["num_x2"],
        heuristic["result_description"]["num_y"],
        heuristic["policy_similarity"]
    ]
    allRoadsDF.loc[allRoadsDF["scenarioID"] == id, solver_cols] = [
        solver["obj_val"]["total_utility"],
        solver["obj_val"]["road_utility"],
        solver["obj_val"]["int_utility"],
        solver["cal_time_sec"],
        solver["result_description"]["num_x1"],
        solver["result_description"]["num_x2"],
        solver["result_description"]["num_y"],
        solver["policy_similarity"]
    ]

In [363]:
naive_cols = ["naive_obj",  "naive_road_u", "naive_int_u", "naive_time", "naive_x1_count", "naive_x2_count", "naive_y_count", "naive_policy_sim"]
heu_cols = ["heu_obj",  "heu_road_u", "heu_int_u", "heu_time", "heu_x1_count", "heu_x2_count", "heu_y_count", "heu_policy_sim"]
solver_cols = ["solver_obj",  "solver_road_u", "solver_int_u", "solver_time", "solver_x1_count", "solver_x2_count", "solver_y_count", "solver_policy_sim"]
newLanesDF = pd.DataFrame(columns = ["scenarioID"] + naive_cols + heu_cols + solver_cols)

for id in range(1, 8):
    with open(f"sol_heuristic/output_h1/scenario_{id}_np/meta_data.json", "r") as file:
        naive = json.load(file)
    with open(f"sol_heuristic/output_h2/scenario_{id}_np/meta_data.json", "r") as file:
        heuristic = json.load(file)
    with open(f"solver/output/scenario_{id}_np/meta_data.json", "r") as file:
        solver = json.load(file)

    newLanesDF.loc[len(newLanesDF), "scenarioID"] = id
    newLanesDF.loc[newLanesDF["scenarioID"] == id, naive_cols] = [
        naive["obj_val"]["total_utility"],
        naive["obj_val"]["road_utility"],
        naive["obj_val"]["int_utility"],
        naive["cal_time_sec"],
        naive["result_description"]["num_x1"],
        naive["result_description"]["num_x2"],
        naive["result_description"]["num_y"],
        naive["policy_similarity"]
    ]
    newLanesDF.loc[newLanesDF["scenarioID"] == id, heu_cols] = [
        heuristic["obj_val"]["total_utility"],
        heuristic["obj_val"]["road_utility"],
        heuristic["obj_val"]["int_utility"],
        heuristic["cal_time_sec"],
        heuristic["result_description"]["num_x1"],
        heuristic["result_description"]["num_x2"],
        heuristic["result_description"]["num_y"],
        heuristic["policy_similarity"]
    ]
    newLanesDF.loc[newLanesDF["scenarioID"] == id, solver_cols] = [
        solver["obj_val"]["total_utility"],
        solver["obj_val"]["road_utility"],
        solver["obj_val"]["int_utility"],
        solver["cal_time_sec"],
        solver["result_description"]["num_x1"],
        solver["result_description"]["num_x2"],
        solver["result_description"]["num_y"],
        solver["policy_similarity"]
    ]

In [364]:
for col in allRoadsDF.columns:
    allRoadsDF[col] = allRoadsDF[col].astype(float)
allRoadsDF = allRoadsDF.round(3)
allRoadsDF["optgap_naive"] = (allRoadsDF["solver_obj"] - allRoadsDF["naive_obj"]) / allRoadsDF["solver_obj"]
allRoadsDF["optgap_heu"] = (allRoadsDF["solver_obj"] - allRoadsDF["heu_obj"]) / allRoadsDF["solver_obj"]
allRoadsDF["scenarioID"] = allRoadsDF["scenarioID"].astype(int).astype(str)
allRoadsDF.set_index("scenarioID", inplace = True)

### All Roads

In [365]:
allRoadsDF[['naive_obj', "heu_obj", "solver_obj", "optgap_naive", "optgap_heu", "naive_time", "heu_time", "solver_time"]]

,naive_obj,heu_obj,solver_obj,optgap_naive,optgap_heu,naive_time,heu_time,solver_time
scenarioID,,,,,,,,
1,871.566,1370.504,3540.033,0.753797,0.612856,0.205,0.717,286.090
2,2246.504,2860.414,6327.466,0.644960,0.547937,0.842,2.950,214.306
3,4930.822,5499.717,10797.093,0.543319,0.490630,1.709,5.467,84.152
4,2194.699,2872.325,5293.731,0.585415,0.457410,0.663,2.057,85.032
5,2142.894,2884.236,4742.554,0.548156,0.391839,0.879,1.689,21.201
6,2248.155,2877.097,6327.565,0.644705,0.545307,0.759,2.147,168.923
7,2280.450,2862.465,6327.655,0.639606,0.547626,0.641,2.220,178.266

In [366]:
allRoadsDF

,naive_obj,naive_road_u,naive_int_u,naive_time,naive_x1_count,naive_x2_count,naive_y_count,naive_policy_sim,heu_obj,heu_road_u,...,solver_obj,solver_road_u,solver_int_u,solver_time,solver_x1_count,solver_x2_count,solver_y_count,solver_policy_sim,optgap_naive,optgap_heu
scenarioID,,,,,,,,,,,,,,,,,,,,,
1,871.566,970.289,846.885,0.205,166.0,4.0,163.0,0.665,1370.504,1368.838,...,3540.033,398.616,3141.417,286.090,533.0,0.0,914.0,0.479,0.753797,0.612856
2,2246.504,2108.357,2281.041,0.842,403.0,7.0,462.0,0.599,2860.414,2892.177,...,6327.466,698.347,5629.119,214.306,922.0,0.0,1634.0,0.468,0.644960,0.547937
3,4930.822,4433.625,5055.122,1.709,926.0,17.0,1147.0,0.528,5499.717,5754.949,...,10797.093,1197.487,9599.606,84.152,1637.0,0.0,2947.0,0.507,0.543319,0.490630
4,2194.699,2108.357,2281.041,0.663,403.0,7.0,462.0,0.599,2872.325,2892.177,...,5293.731,1844.721,3449.010,85.032,904.0,27.0,1613.0,0.479,0.585415,0.457410
5,2142.894,2108.357,2281.041,0.879,403.0,7.0,462.0,0.599,2884.236,2892.177,...,4742.554,3856.639,885.915,21.201,464.0,303.0,1055.0,0.461,0.548156,0.391839
6,2248.155,2193.974,2261.700,0.759,394.0,11.0,458.0,0.604,2877.097,3070.617,...,6327.565,697.240,5630.325,168.923,920.0,0.0,1633.0,0.470,0.644705,0.545307
7,2280.450,2054.540,2336.927,0.641,413.0,4.0,474.0,0.594,2862.465,2751.260,...,6327.655,698.244,5629.411,178.266,926.0,0.0,1650.0,0.471,0.639606,0.547626

In [367]:
for col in newLanesDF.columns:
    newLanesDF[col] = newLanesDF[col].astype(float)
newLanesDF = newLanesDF.round(3)
newLanesDF["optgap_naive"] = (newLanesDF["solver_obj"] - newLanesDF["naive_obj"]) / newLanesDF["solver_obj"]
newLanesDF["optgap_heu"] = (newLanesDF["solver_obj"] - newLanesDF["heu_obj"]) / newLanesDF["solver_obj"]
newLanesDF["scenarioID"] = newLanesDF["scenarioID"].astype(int).astype(str) + "_np"
newLanesDF.set_index("scenarioID", inplace = True)

### Only Consider Roads without Bike Lanes

np refers to new policy

In [368]:
newLanesDF[['naive_obj', "heu_obj", "solver_obj", "optgap_naive", "optgap_heu", "naive_time", "heu_time", "solver_time"]]

,naive_obj,heu_obj,solver_obj,optgap_naive,optgap_heu,naive_time,heu_time,solver_time
scenarioID,,,,,,,,
1_np,72.849,212.338,735.837,0.900998,0.711433,0.028,0.078,20.028
2_np,287.001,521.656,1360.648,0.789070,0.616612,0.067,0.202,22.467
3_np,487.461,734.942,1899.644,0.743393,0.613116,0.141,0.401,19.161
4_np,318.507,546.004,1172.388,0.728326,0.534280,0.073,0.192,12.305
5_np,350.014,570.352,1110.978,0.684950,0.486622,0.062,0.230,2.845
6_np,276.683,532.686,1360.648,0.796654,0.608506,0.068,0.318,22.888
7_np,287.001,529.071,1360.648,0.789070,0.611162,0.069,0.203,24.047

# Fake Data

In [369]:
full = pd.DataFrame()
for file in os.listdir("./Experiments/outputs"):
    data = pd.read_excel(f"./Experiments/outputs/{file}", index_col=0)
    full = pd.concat([full, data])

In [373]:
full.columns

Index(['scenarioID', 'naiveObjVal', 'naiveTime', 'naiveX1num', 'naiveX2num',
       'naiveYnum', 'heuObjVal', 'heuTime', 'heuX1num', 'heuX2num', 'heuYnum',
       'solverObjVal', 'solverTime', 'solverX1num', 'solverX2num',
       'solverYnum', 'optGapNaive', 'optGapHeu'],
      dtype='object')

In [376]:
result = full.groupby("scenarioID").agg({
    "naiveObjVal": ["mean", "std"],
    "naiveTime": ["mean", "std"],
    "heuObjVal": ["mean", "std"],
    "heuTime": ["mean", "std"],
    "solverObjVal": ["mean", "std"],
    "solverTime": ["mean", "std"],
    "optGapNaive": ["mean", "std"],
    "optGapHeu": ["mean", "std"]
})
result

            naiveObjVal             naiveTime              heuObjVal  \
                   mean         std      mean       std         mean
scenarioID
1            587.872206   35.804664  0.218277  0.030711  1233.543017
2           1238.474015   44.719974  0.523410  0.086311  2469.287288
3           2816.530371   92.002530  1.761396  0.593736  4902.578937
4           2561.448408  134.328708  0.546960  0.182712  2866.443335
5           3949.485693  212.412369  0.564530  0.123804  3290.988395
6           1336.203447   79.479847  0.511078  0.127436  2534.220448
7           1151.250805   53.044918  0.550468  0.097955  2447.963429
1_np         108.791868   21.281927  0.035762  0.013502   231.176665
2_np         217.893470   23.094178  0.067839  0.019185   449.349732
3_np         329.029024   20.862980  0.101002  0.023159   675.975656
4_np         544.978173   80.797574  0.076198  0.027884   540.737048
5_np         877.121961  105.649423  0.064602  0.015691   641.357310
6_np         240.115745   33.634513  0.062357  0.015395   455.766954
7_np         210.320043   23.136336  0.128578  0.090276   444.967743

                         heuTime            solverObjVal             \
                   std      mean       std          mean        std
scenarioID
1            52.292943  0.767672  0.125419   3791.616904  48.244173
2            96.715167  1.710857  0.239983   6766.533337  57.718374
3           128.939043  4.608333  1.183900  11516.439314  89.698708
4           102.082712  1.677870  0.391229   5289.846300  49.747739
5           150.502261  1.707277  0.306812   4811.568085  72.213634
6            94.204371  1.628032  0.253725   6766.439185  84.619459
7            89.495336  1.767199  0.228985   6773.586659  69.371546
1_np         21.544236  0.114200  0.054498    727.023866  21.324637
2_np         34.856848  0.217972  0.082337   1318.901806  30.984777
3_np         29.951529  0.312061  0.069675   1843.582198  43.482976
4_np         44.849294  0.223754  0.071479   1101.539091  23.092924
5_np         70.538411  0.196442  0.044315   1218.758194  31.147321
6_np         45.246874  0.187680  0.056082   1315.261277  28.109068
7_np         35.550708  0.346360  0.160647   1315.180099  25.078974

           solverTime           optGapNaive           optGapHeu
                 mean       std        mean       std      mean       std
scenarioID
1            4.927344  0.507258    0.844934  0.009629  0.674624  0.014170
2            5.339021  0.952326    0.816977  0.006220  0.635075  0.013911
3            5.745889  1.179475    0.755425  0.008047  0.574294  0.010829
4            5.140368  0.891097    0.515739  0.025802  0.458057  0.020366
5            4.946790  0.421078    0.179156  0.042844  0.315904  0.032232
6            5.116529  1.060642    0.802537  0.011259  0.625447  0.013910
7            4.763544  0.349662    0.830036  0.007686  0.638584  0.013160
1_np         1.478521  0.273136    0.850086  0.030866  0.681826  0.030338
2_np         1.563660  0.267635    0.834670  0.018345  0.659063  0.028414
3_np         1.627679  0.262029    0.821368  0.013035  0.633175  0.017794
4_np         1.521196  0.187778    0.504626  0.077287  0.508917  0.041824
5_np         1.377817  0.195111    0.279133  0.093516  0.472934  0.063948
6_np         1.587217  0.289502    0.817398  0.025248  0.653611  0.032054
7_np         2.098111  0.610576    0.839960  0.018466  0.661672  0.026157

In [377]:
result.to_excel("Experiments/result_table.xlsx")