In [5]:
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import geopandas as gpd

## Road Data

Load the data: use `gpd.read_parquet()`

Data Schema:

- `roadID`             : i, road id in order
  
- `roadID_foreign`     : road id from original raw file
  
- `roadName`          : road name
  
- `geometry`           : geometry column for this gdf (in shapely.geometrhPolygon often)
  
- `centroid`           : the center of the road (shapely.geometry.Point)
  
- `roadDemand`         : demand of road i, calculated by the centroid
  
- `roadDemand_m2` : demand of road i, calculated by averaging the demand of several points on the road
  
- `width`    : road width
  
- `length`   : road length
  
- `danger`   : degree of danger of road i, calculated by the centroid
 
- `danger_m2`: danger of road i, calculated by averaging the demand of several points on the road
  
- `roadDemand_m2_norm` : normalized roadDemand_m2, constant 3 is added to ensure positive value
  
- `danger_m2_norm`: normalized danger_m2, constant 3 is added to ensure positive value


To calculate the utility of road i ($u_i^{road}$ in obj. function), we calculate the following:

$$\alpya$$

In [9]:
gpd.read_parquet("./processed/road_data.parquet").head(2)

,roadID,roadID_foreign,roadName,geometry,centroid,roadDemand,roadDemand_m2,width,length,danger,danger_m2,roadDemand_m2_norm,danger_m2_norm
0,1,南深路-31,南深路,"POLYGON ((121.62348 25.0182, 121.6234 25.01805...",POINT (121.6231981462958 25.017423573687317),2473.216309,2548.270996,17.5733,185.594,1,1.0,1.698332,2.377554
1,2,南深路-30,南深路,"POLYGON ((121.62292 25.01926, 121.62296 25.019...",POINT (121.62320858388321 25.018891469451464),2626.366699,2626.366699,14.5230,175.571,1,1.0,1.703311,2.377554

## Adjacency Matrix

Load the data: use `gpd.read_parquet()`

\# Note that this file only contant adjacent road pairs! Road pair that is not adjacent is not contained.

data schema:

- `road_i`: index of road i, could be referred to the `roadID` column in road_data.parquet
  
- `road_j`: index of road j, could be referred to the `roadID` column in road_data.parquet
  
- `intersection_geom`: the geometry of the intersection of road i and j.
  
- `intersection_demand`: the demand of the intersection. For more details for calculation, please refer to `roadProcessing/computeAdjacency.py`
  
- `intersection_demand_norm`: normalized intersection demand, added by constant 3 to ensure positive value

In [12]:
gpd.read_parquet("./processed/adjacency_demand.parquet").head(5)

,road_i,road_j,intersection_geom,intersection_demand,intersection_demand_norm
0,21,26,"LINESTRING (121.61271 25.03356, 121.61274 25.0...",6643.267578,1.734957
1,21,29,"LINESTRING (121.61251 25.03348, 121.61265 25.0...",6902.702637,1.751566
2,22,29,"LINESTRING (121.61229 25.03339, 121.61243 25.0...",6902.702637,1.751566
3,23,26,"LINESTRING (121.61283 25.03362, 121.61284 25.0...",6643.267578,1.734957
4,24,30,POINT (121.60985 25.03395),7746.741211,1.805600

## MRT station data 

This data is for the constraint **C2** (Area Coverage Constraint). Use MRT station as the proxy of important facilities.

data schema (important columns only):

- `geometry`: geometry column for the station (in lat, lon coordinate)
  
- `x_m`: the x coordinate, transformed from lat, lon (so as to calculate Euclidean distance with road)
  
- `y_m`: the y coordinate, transformed from lat, lon (so as to calculate Euclidean distance with road)

In [14]:
gpd.read_parquet("./processed/mrt_stations.parquet").head(5)

,wkt_geom,MARKID,MARKTYPE1,MARKTYPE2,MARKNAME1,MARKNAME2,異動日期_西元年月,ADDRESS,TEL,坐標系統,geometry,x_m,y_m
219,Point (304292.58899999968707561 2761254.992000...,F0000003261,9960103,NaN,臺北捷運新店站_G01,北捷新店站_G01,201904,新北市新店區北宜路一段2號,02-218-12345,TM2,POINT (121.53768 24.9582),-2702.031253,-8784.257307
220,Point (304297.5849999999627471 2761256.4240000...,F0000003151,9960103,NaN,臺北捷運新店站-出入口,北捷新店站-出入口,201904,新北市新店區北新路一段與北宜路一段交叉口,None,TM2,POINT (121.53773 24.95821),-2697.029023,-8782.846000
221,Point (292262.35800000000745058 2761299.676000...,F0000010541,9960103,NaN,臺北捷運頂埔站-出入口2,北捷頂埔站-出入口2,202201,新北市土城區中央路四段，近鴻海精密工業,None,TM2,POINT (121.41855 24.95898),-14732.831395,-8689.542676
222,Point (292262.8880000002682209 2761319.2390000...,F0000000573,9960103,NaN,臺北捷運頂埔站_BL01,北捷頂埔站_BL01,201906,新北市土城區中央路四段51之6號B3,02-218-12345,TM2,POINT (121.41855 24.95916),-14732.220008,-8669.980507
223,Point (292241.46999999973922968 2761339.161000...,F0000009516,9960103,NaN,臺北捷運頂埔站-出入口1,北捷頂埔站-出入口1,202201,新北市土城區中央路四段約100號旁,None,TM2,POINT (121.41834 24.95934),-14753.556655,-8649.968021

In [ ]:
img = mpimg.imread("your_image.png")  # Load PNG
plt.imshow(img)
plt.axis("off")  # optional: hide axes
plt.show()